version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - fintech
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - fintech

  api:
    image: api:1.0.0
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - fintech-mysql
      - fintech-redis
    networks:
      - fintech

  consumer:
    image: consumer:1.0.0
    container_name: consumer
    ports:
      - "8081:8081"
    depends_on:
      - fintech-mysql
      - fintech-redis
      - kafka
    networks:
      - fintech

  css:
    image: css:1.0.0
    container_name: css
    ports:
      - "8082:8082"
    networks:
      - fintech

  nginx:
    image: nginx:1.0.0
    container_name: nginx
    ports:
      - "8085:8085"
    networks:
      - fintech

# mysql connection 문제로인해 추가 (같은 네트워크지만 따로 생성하면 연결 못하는 문제 발생)
  fintech-mysql:
    image: mysql:latest
    container_name: fintech-mysql
    environment:
      MYSQL_DATABASE: fintech
      MYSQL_USER: fintech
      MYSQL_PASSWORD: fintech
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - fintech

  fintech-redis:
    image: redis:latest
    container_name: fintech-redix
    ports:
      - "6379:6379"
    networks:
      - fintech

networks:
  fintech:
    driver: bridge